"""Pseudonyms for hiding people names in demo mode."""

import hashlib

ADJECTIVES = [
    "Active",
    "Airborne",
    "All-encompassing",
    "Amber",
    "Attentive",
    "Amiable",
    "Aquatic",
    "Arboreal",
    "Blue",
    "Bold",
    "Brave",
    "Calm",
    "Camouflaging",
    "Careful",
    "Cheerful",
    "Clandestine",
    "Clever",
    "Comical",
    "Comprehensive",
    "Confident",
    "Confused",
    "Creative",
    "Curious",
    "Cyan",
    "Diurnal",
    "Fast",
    "Famous",
    "Fastidious",
    "Fierce",
    "Fragrant",
    "Gentle",
    "Gigantic",
    "Grand",
    "Green",
    "Hidden",
    "Imaginative",
    "Jealous",
    "Jiggly",
    "Judicious",
    "Large",
    "Lemony",
    "Living",
    "Loud",
    "Lucky",
    "Luddite",
    "Nocturnal",
    "Noisy",
    "Nosy",
    "Omniferous",
    "Omnipresent",
    "Omnipotent",
    "Omniscient",
    "Oozing",
    "Orange",
    "Ornamental",
    "Playful",
    "Prescient",
    "Proud",
    "Prudent",
    "Quiet",
    "Red",
    "Sage",
    "Sensible",
    "Serendipitous",
    "Serene",
    "Silent",
    "Sleepy",
    "Sour",
    "Squishy",
    "Swift",
    "Timid",
    "Tiny",
    "Transparent",
    "Underwater",
    "Urban",
    "Wandering",
    "Wary",
    "Weary",
    "Whispering",
    "Wise",
    "Worried",
    "Yellow",
    "Zealous",
]
ANIMALS = [
    "Ant",
    "Armadillo",
    "Bear",
    "Badger",
    "Bison",
    "Butterfly",
    "Cat",
    "Caterpillar",
    "Chicken",
    "Centipede",
    "Crab",
    "Crow",
    "Cuckoo",
    "Deer",
    "Dolphin",
    "Dragonfly",
    "Eagle",
    "Earthworm",
    "Eel",
    "Elephant",
    "Falcon",
    "Firefly",
    "Flea",
    "Fly",
    "Fox",
    "Frog",
    "Giraffe",
    "Groundhog",
    "Hedgehog",
    "Heron",
    "Horse",
    "Jellyfish",
    "Kangaroo",
    "Kiwi",
    "Koala",
    "Ladybug",
    "Lynx",
    "Magpie",
    "Mantis",
    "Meerkat",
    "Mouse",
    "Mussel",
    "Octopus",
    "Otter",
    "Owl",
    "Panda",
    "Plankton",
    "Rabbit",
    "Rat",
    "Raven",
    "Ray",
    "Sardine",
    "Scorpion",
    "Seaslug",
    "Shark",
    "Sky Bison",
    "Slug",
    "Snail",
    "Snake",
    "Sparrow",
    "Spider",
    "Sponge",
    "Squirrel",
    "Starfish",
    "Urchin",
    "Wasp",
    "Whale",
    "Wolf",
    "Zebra",
]


def pseudonym_for_id(person_id: str) -> str:
    digest = hashlib.md5(person_id.encode()).hexdigest()
    n = int(digest, 16)
    adjective = ADJECTIVES[n % len(ADJECTIVES)]
    animal = ANIMALS[(n // len(ADJECTIVES)) % len(ANIMALS)]
    return f"{adjective} {animal}"


def resolve_name(person_id, real_name, demo_mode):
    if demo_mode:
        return pseudonym_for_id(person_id)
    return real_name or person_id
